name: vipdopt-dev
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11.*
  - scipy=1.11.*
  - numpy=1.25.*
  - matplotlib=3.7.*
  - scikit-image=0.20.*
  - PyYAML
  - types-PyYAML
  - python-magic
  - dill
  - Jinja2
  - pip
  - PySide6=6.6.1
  - QtPy=2.4.1
  # For Linting
  - ruff=0.0.287
  # For static type checking
  - mypy=1.5.*
  - overrides=7.4.*
  # For testing
  - pytest=7.4.*
  - pytest-cov=4.1.*
  - pytest-xdist=3.3.*
  - pytest-mock
  - coverage[toml]=7.2.*