[tool.ruff]
fix = true
show-fixes = true

# Enable the pycodestyle (`E`) and Pyflakes (`F`) rules by default.
# Unlike Flake8, Ruff doesn't enable pycodestyle warnings (`W`) or
# McCabe complexity (`C901`) by default.
select = ["E", "F"]
ignore = []

# Allow autofix for all enabled rules (when `--fix`) is provided.
fixable = ["ALL"]

# Exclude a variety of commonly ignored directories.
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "venv",
]

# Same as Black.
line-length = 88

# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

# Assume Python 3.11
target-version = "py311"

# Ignore `E402` (import violations) in all `__init__.py` files and in other folders
[tool.ruff.per-file-ignores]
"**/__init__.py" = ["E402", "F403"]
"**/{tests,testing,docs}/*" = ["E402"]

[tool.ruff.flake8-quotes]
docstring-quotes = "double"
inline-quotes = "single"

[tool.ruff.flake8-pytest-style]
parametrize-names-type = "csv"
parametrize-values-type = "tuple"

[tool.pytest.ini_options]
markers = [
    "smoke: mark tests as smoke if unit-testing for regressions",
    "slow: mark tests as slow (only run with full suite)"
]

testpaths = ["tests"]