#
# Ruff Settings
#

[tool.ruff]
fix = true
show-fixes = true

select = ["E", "F", "W", "I", "N", "D", "UP", "BLE", "FBT", "B", "A", "COM", "CPY",
    "C4", "ISC", "ICN", "PIE", "T20", "PT", "Q", "RSE", "RET", "SLF", "SIM", "TID",
    "ARG", "ERA", "PL", "TRY", "NPY", "PERF", "FURB", "RUF"]
ignore = [
    "ANN",  # Type hints / annotations; handled by mypy
    "COM812",  # "Trailing Comma Missing"
    "TRY003",  # "Avoid specifying long messages outside the exception class"
]

# Allow autofix for all enabled rules (when `--fix`) is provided.
fixable = ["ALL"]

# Exclude a variety of commonly ignored directories.
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "venv",
]

# Same as Black.
line-length = 88

# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

# Assume Python 3.11
target-version = "py311"

[tool.ruff.per-file-ignores]
# Ignore import violations in all `__init__.py` files and in other relevant folders
"**/__init__.py" = ["E402", "F403", "F405"]
"**/{testing,docs}/*" = ["E402"]

# Ignore documentation for tests
# Ignore boolean arguments in methods for tests
"**/tests/*" = ["E402", "D", "FBT001"]

[tool.ruff.flake8-quotes]
docstring-quotes = "double"
inline-quotes = "single"

[tool.ruff.flake8-pytest-style]
parametrize-names-type = "csv"
parametrize-values-type = "list"

[tool.ruff.pydocstyle]
# Use Google-style docstrings.
convention = "google"

# Ignore things with certain decorators
ignore-decorators = ["overrides.override"]
property-decorators = ["abc.abstractproperty"]

[tool.ruff.mccabe]
max-complexity = 15

#
# Pytest Settings
#

[tool.pytest.ini_options]
 markers = [
    "smoke: these tests should always run to check for regressions quickly",
    "slow: mark tests as slow (only run with full suite)"
]

testpaths = ["tests"]


#
# Coverage Settings
#

[tool.coverage.run]
branch = true
source = ["vipdopt"]

[tool.coverage.report]
# Regexes for lines to exclude from consideration
exclude_also = [
    # Don't complain about missing debug-only code:
    "def __repr__",
    "if self\\.debug",

    # Don't complain if tests don't hit defensive assertion code:
    "raise AssertionError",
    "raise NotImplementedError",

    # Don't complain if non-runnable code isn't run:
    "if 0:",
    "if __name__ == .__main__.:",
    "pass",

    # Don't complain about abstract methods, they aren't run:
    "@(abc\\.)?abstractmethod",
    ]

ignore_errors = true
