name: Setup Python and Cache Dependencies

inputs:
  python-version:
    required: true
    default: 3.11
  cache:
    required: true 
    default: 'pip'
  cache-dependency-path:
    required: true 
    default: './requirements.txt'
    
  runs:
    using: composite
    steps:
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ INPUT_PYTHON-VERSION }}
          cache: ${{ INPUT_CACHE }}
          cache-dependency-path: ${{ INPUT_CACHE-DEPENDENCY-PATH}}

      - name: Install Dependencies 
        run: |
          for file in ${{ INPUT_CACHE-DEPENDENCY-PATH }}
          do
            pip install -r file
          done
