name: Setup Python and Install All Dependencies

inputs:
  python-version:
    required: false
    default: 3.11
  cache:
    required: false 
    default: 'pip'
  cache-dependency-path:
    required: false
    default: '*requirements.txt'
    
runs:
  using: composite
  steps:
    - name: Setup python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}
        cache: ${{ inputs.cache }}
        cache-dependency-path: ${{ inputs.cache-dependency-path }}

    - name: Install Dependencies 
      shell: bash
      run: |
        for file in ${{ inputs.cache-dependency-path }}
        do
          pip install -r $file
        done
