name: CI
on:
  push:
    branches:
      - main
      - cleanup
  pull_request:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
    
      - name: Setup python
        uses: actions/setup-python@v3
        with:
          python-version: '3.11'
    
      - name: Install Linter Requirements
        run: python -m pip install -r linter_requirements.txt

      - name: Lint
        uses: wearerequired/lint-action@v1
        with:
          auto_fix: true
          black: true
          black_args: --exclude tests
          flake8: true

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
    
      - name: Setup python
        uses: actions/setup-python@v3
        with:
          python-version: '3.11'
    
      - name: Install dependencies
        run: |
          python -m pip install -r build_requirements.txt
          python -m pip install -r test_requirements.txt
    
      - name: Run tests
        run: python -m pytest

  mypy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
    
      - name: Setup python
        uses: actions/setup-python@v3
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install -r build_requirements.txt
          python -m pip install -r test_requirements.txt
    
      - name: Run MyPy 
        run: mypy vipdopt tests testing
 