nmae: Linting, Formating, Type Checking
on: [push, pull_request]
jobs:
  setup:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Conda Environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: vipdopt-dev
          environment-file: environment.yml
          python-version: 3.11
          auto-activate-base: false
      
        run: |
          conda info
          conda list
  lint:
    needs: setup
    runs-on: ubuntu-latest
    uses: wearrerequired/lint-action@v1
    with:
      auto_fix: true
      black: true
      black_args: --exclude tests
      flake8: true
  type_check:
    needs: setup
    runs-on: ubuntu-latest
    uses: jakebailey/pyright-action@v1
    with:
      working-directory: vipdopt
