name: Linux Continuous Integration

# This file is intended for testing on linux platforms, running benchmarks, measuring
# code coverage, etc.

on: [push, pull_request]


permissions:
  contents: read # to fetch code (actions/checkout)


concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true


jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
    
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
    
      - name: Install ruff
        run: python -m pip install ruff

      - name: Lint with ruff
        uses: chartboost/ruff-action@v1
        with:
          src: 'vipdopt tests'
          args: --config pyproject.toml

  smoke-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup MPI
        uses: mpi4py/setup-mpi@v1
    
      - name: Setup Python
        uses: ./.github/actions/python-setup
    
      - name: Run Smoke Tests
        run: pytest -m 'smoke'
