name: Run MyPy

# Mypy is too slow to run as part of regular CI. The purpose of the jobs in
# this file is to cover running Mypy across:
#
#   - OSes: Linux, Windows and macOS
#   - Python versions: lowest/highest supported versions, and an intermediate one

on:
  push:
    branches:
      - main
      - cleanup
  pull_request:


concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true


permissions:
  contents: read # to fetch code (actions/checkout)


jobs:
  mypy:
    name: "MyPy"
    runs-on: ${{ matrix.os_python[0] }}
    strategy:
      matrix:
        os_python:
          - [ubuntu-latest, '3.11']  # switch to 3.12-dev after mypy is upgraded (see gh-23764)
          - [windows-2019, '3.11.1']
          - [macos-12, '3.11.2']
    steps:
      - uses: actions/checkout@v4

      - name: Setup python
        uses: ./.github/actions/python-setup
        with:
          python-version: ${{ matrix.os_python[1] }}
          cache: 'pip'
          cache-dependency-path: './*_requirements.txt'
    
      - name: Python magic bin install
        if: contains(${{ matrix.os_python[0] }}, 'windows') or contains(${{ matrix.os_python[0] }}, 'macos')
        run: |
            pip install python-magic-bin

      - name: Run MyPy 
        run: |
          mypy vipdopt
