name: Tests and Code coverage

on:
  push:
    branches:
      - main
      - cleanup
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
    tests:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v4

        #   - name: Setup python
        #     uses: ./.github/actions/python-setup
        #     with:
        #         python-version: '3.11'
        #         cache: 'pip'
        #         cache-dependency-path: './*_requirements.txt'
          - name: Setup python
            uses: actions/setup-python@v4
            with:
                python-version: '3.11'
                cache: 'pip'
                cache-dependency-path: '*requirements.txt'
        
          - name: Install Dependencies 
            shell: bash
            run: |
                pip install -r build_requirements.txt
                pip install -r test_requirements.txt
        
          # TODO: Increase fail percentage to 90
          - name: Get coverage information and test above threshold
            run: pytest --cov=vipdopt --cov-report term-missing --cov-fail-under 80
