name: Tests and Code coverage

on:
  push:
    branches:
      - main
      - cleanup
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
    tests:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v4

          - name: Setup python
            uses: ./.github/actions/python-setup
            with:
                python-version: '3.11'
                cache: 'pip'
                cache-dependency-path: './*_requirements.txt'
        
          # TODO: Increase fail percentage to 90
          - name: Get coverage information and test coverage
            run: |
              coverage --version
              coverage run -m pytest -n auto
              coverage report -m --fail-under 80
        