name: Tests and Code coverage

# Runs all tests (except for  MPI) and generates a coverage report.defaults:
# Job fails if less than 85 percetn coverage

on:
  push:
    branches:
      - main
      - dev
  pull_request:


concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
    check_coverage:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout Repository
            uses: actions/checkout@v4

          - name: Setup Python
            uses: ./.github/actions/python-setup
        
          - name: Check Coverage
            run: pytest -m "not lumapi" --cov-config=pyproject.toml --cov
